### ISSUE TITLE
syphon would be nice

### ISSUE THREAD

**Issue by MacroMachines** [danomatika/loaf#1]
I figure with OSC and syphon, that's all you really need to intercommunicate.

**Comment by danomatika** [comment]
I don't plan to add any extra addons to the core of loaf. The general idea is to support dynamically loading pre-compiled addons as Lua plugins, although I've not gone into this too much in depth yet.

**Comment by dom1817** [comment]
Besides being able to share GPU textures across different softwares as @MacroMachines say, Syphon also offers an easy way [to record video output](http://syphon.v002.info/recorder/). That would be a useful feature for Loaf.

**Comment by danomatika** [comment]
I agree it could be useful, but this is really a non-core requirement. There are *lots* of addons that could be useful to have, but then the project becomes massive.

This is better solved by building ofxSyphon as a dynamic Lua module via a Makefile. I don't have an example of this, but I did some quick testing with ofxOsc years ago and it was possible.

**Comment by danomatika** [comment]
I've been playing around with building addons as dynamic models to use with loaf. Syphon seemed like a good target to start and it's more or less working, although the makefile needs some cleanup and testing.

<img width="1280" alt="Screen Shot 2020-12-18 at 3 21 14 AM" src="https://user-images.githubusercontent.com/480637/102566732-6538b800-40e0-11eb-8cb8-a2799d07f6d9.png">

**Comment by danomatika** [comment]
You can try the example ofxSyphon module here: https://github.com/danomatika/ofxLua/tree/master/modules

Build the module, then you can load it via `require "syphon"`. See the small test.lua script.

**Comment by danomatika** [comment]
Note: loaf may crash using the syphon module if the script is reloaded, either manually or by the file change watcher mechanism. I'm not sure why yet. The `--ignore` command line flag can be used to disable the watcher.

**Comment by danomatika** [comment]
After going down the modules rabbit-hole, I've found that SWIG does not recommend nor support mixing static and dynamic modules. This is unfortunate as it means using the syphon module is unstable, hence the crash on reload. The fix is either to make the of and gem modules dynamic or compile the syphon module into loaf like the osc module. *sigh*

**Comment by danomatika** [comment]
Ok, Syphon support added with loaf 1.6.0. I've tested on macOS 10.14.6 with the Syphon Recorder application.

The macOS build is here: http://docs.danomatika.com/releases/loaf/loaf-1.6.0-macos.zip

The overview is here: https://github.com/danomatika/loaf#syphon-support

There are also command line options to start the built-in server and set it's name.
