### ISSUE TITLE
Open loaf from VS code and get console output

### ISSUE THREAD

**Issue by latenitecali** [danomatika/loaf#11]
Hello, wondering if there's a way to launch loaf from VS code and get console output there too. I can dig into the Package Contents 'folder' of the app and launch a terminal window from there, but it's kind of cumbersome. Looking for a way to have it all in Code. Thanks!

**Comment by latenitecali** [comment]
also, an example of how to set up soundStream or audio input would be awesome =]

**Comment by danomatika** [comment]
> Hello, wondering if there's a way to launch loaf from VS code and get console output there too. I can dig into the Package Contents 'folder' of the app and launch a terminal window from there, but it's kind of cumbersome. Looking for a way to have it all in Code. Thanks!

The readme describes how to launch loaf from the command line. It then outputs via stdout, so I imagine you can treat it like any other console application within Code, ie. the output would go to the Code console pane (or whatever they have). I use loaf from the command line directly and I use Sublime Text for editing. I suggest checking the VS Code documentation on how to loop in a command into their environment.

**Comment by danomatika** [comment]
> also, an example of how to set up soundStream or audio input would be awesome =]

(This is a separate issue/request but I will answer here.)

ofSoundStream is not wrapped in the Lua bindings as I assumed it would be too slow for working with samples on the audio thread. @okyeron however [seems to have some luck with it](https://github.com/danomatika/loaf/issues/10#issuecomment-1470236907), so I may include bindings for it in a subsequent loaf version.

**Comment by latenitecali** [comment]
Thanks for the responses. I was able to launch from Code's terminal pane, but it just launches a Terminal instance and output goes there. Not a big deal at all, that works just fine. As for the soundstream stuff, Steve sent me here so I'll just go back to bugging him on discord 😂

**Comment by danomatika** [comment]
Which path do you use? Launching from a normal Terminal instance open within the same instance, no separate window. If you invoking via open or double-click on MacOS/loaf it indeed opens a new Terminal window.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by latenitecali** [comment]
....got to love computers sometimes. Today, I tried `./loaf.app/Contents/MacOS/loaf` from Code's terminal window, and it launches fine with output staying there. I must have had something mixed up yesterday.

**Comment by danomatika** [comment]
Closing this for now
