### ISSUE TITLE
OSC typo in helloword.lua

### ISSUE THREAD

**Issue by jeromeabel** [danomatika/loaf#3]
In the helloword.lua script, I had to change these conditions (lines 43 and 45)
`
if message.address == "/circle/x"
` 
in

`
if message:getAddress() == "/circle/x"
`

**Comment by danomatika** [comment]
Is that from the zip download? It's already fixed in the repo.

**Comment by danomatika** [comment]
Whoops, never mind. I fixed it locally a while ago and forgot to push.

**Comment by jeromeabel** [comment]
I don't remember. Best.
