### ISSUE TITLE
How to access C++ vectors in Loaf

### ISSUE THREAD

**Issue by dom1817** [danomatika/loaf#4]
I'm trying to access a vector containing the list of vertices of a polyline. I can run the following script and get the results in my Lua variable, but I don't know how to access this «userdata».

```
local line = of.Polyline()
local vertices = line:getVertices()
```
I tried many combinations to read the `vector<glm::vec3>` type but I only get this error:
```
[ error ] loaf: script.lua: attempt to index a userdata value (local 'vertices')
```
Is there a way to access this kind of data?

**Comment by danomatika** [comment]
`std::vector<ofDefaultVertexType>` wasn't being wrapped, so it only translated as a raw pointer.

This is fixed now in loaf 1.4.4 so the following works as expected:

~~~
local line = of.Polyline()

function setup()
	line:curveTo(200, 100)
	line:curveTo(200, 200)
	line:curveTo(100, 200)
	line:curveTo(100, 100)
	local vertices = line:getVertices()
	print(vertices:size())
	for i=0,vertices:size()-1 do
		local v = vertices[i]
		print(i.." "..tostring(v))
	end
end

function draw()
	line:draw()
end
~~~

_Note: The wrapped std::vector still uses 0-indexing while Lua tables are 1-indexed._

So far, I haven't used any of the vector types directly, so you may find other issues like this.

**Comment by dom1817** [comment]
Thank you for fixing this so fast, it works perfectly. I'm realizing just now that to erase elements from that vector I would also need to use iterators and modifiers in Loaf and probably this won't be possible at the moment.

On the other hand, I also thought that making a Lua table of ofPoint is just easier. This way I can write all the sorting methods I want in Lua, without depending too much on wrappers, and I can eventually add the vertices to my ofPolyline by looping through the table. Not efficient maybe, but works very well for me.

**Comment by danomatika** [comment]
In general, I use the of class getters/setters in Lua instead of the vectors, ie. ofPixels:getColor(x, y). A more advanced typemap could be written to make this seamless, but it's a good amount of work and I didn't need vector access so far.

**Comment by danomatika** [comment]
As for performance, I haven't run into anything which has slowed me down in Lua yet, although most of what I'm using loaf for is not especially intensive.

**Comment by dom1817** [comment]
> I use the of class getters/setters in Lua instead of the vectors

I totally agree and I think it's actually weird that there is an _addVertex()_ method, but not a _removeVertex()_ in the ofPolyline class. This method [is defined](https://github.com/openframeworks/openFrameworks/blob/b34f9a936badb4b9667daaa90d16e719fab8eb03/libs/openFrameworks/3d/ofMesh.inl#L351) in the ofMesh class and does exactly what one would expect:

`vertices.erase(vertices.begin() + index);`

I could have done everything I needed in Loaf by just using that method, without dealing directly with vectors or iterators. I don't know, I'm quite new to openFrameworks and I guess they have a good reason for this.

**Comment by danomatika** [comment]
>I totally agree and I think it's actually weird that there is an addVertex() method, but not a removeVertex() in the ofPolyline class.

You could open an issue on the main OF repo and in the meantime I can make a class extension which adds this in the wrapper.

**Comment by dom1817** [comment]
That's great, I just opened the [issue](https://github.com/openframeworks/openFrameworks/issues/6375) on the main repository.

**Comment by danomatika** [comment]
Try loaf 1.4.5beta which [adds a removeVertex() extension](https://github.com/danomatika/swig-openframeworks/blob/ccd6b66dbb17f4149d14d9fcba50f72a78f545b5/openFrameworks/openFrameworks/graphics.i#L138).

**Comment by danomatika** [comment]
>I could have done everything I needed in Loaf by just using that method, without dealing directly with vectors or iterators. I don't know, I'm quite new to openFrameworks and I guess they have a good reason for this.

One reason is that OF has been moving towards much more usage of C++isms which are quicker to use implicitly in C++ but *much harder* to wrap for scripting languages than explicit functions, ie. iterators -> foreach versus size(), get(), set(), etc.

**Comment by dom1817** [comment]
I just tried Loaf 1.4.5 and removeVertex() works perfectly, thank you!
