### ISSUE TITLE
A few other C++ vectors might need to be wrapped (ofPolyline, ofPath)

### ISSUE THREAD

**Issue by dom1817** [danomatika/loaf#5]
This structure seems to be quite common in openFrameworks:
`vector<ofPath>` → `vector<ofPolyline>` →` vector<ofVertex>`

A use case with a similar structure that I was trying to use in Loaf is:
`vector<ofPath> characters = font.getStringAsPoints(text)`
Then:
`vector <ofPolyline> outlines = characters[n].getOutline()`
Then:
`vector <ofVertex> vertices = outlines[n]`

Now that vectors of vertices or points are [now](https://github.com/danomatika/loaf/issues/4) accessible, wrapping also the other containers would be a great addition to Loaf.

```lua
-- Define font
font = of.TrueTypeFont()
font:load("filename.ttf", 32)

-- Print each vertex of a character
characters = font:getStringAsPoints("Hello")
for i=0,characters:size() do
    outlines = characters[i]
    for n=0, outlines:size() do
        vertices = outlines[n]
        for m=0, vertices:size() do
            of.drawCircle(vertices[m],10)
        end
    end
end
```

**Comment by danomatika** [comment]
Ok. Can you provide a list? That would be the easiest for me, other than looking through the API again.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by dom1817** [comment]
### ofPolyline
- [x] **ofPolyline:getVertices() → vector(ofVertex)**
Fixed in previous commit.

### ofPath

- [x] **ofPath:getOutline() → vector(ofPolyline)**
This function returning a vector of polylines is already working:
```lua
path = of.Path()
    -- Make first polyline
    path:lineTo(0,0) 
    [...]
    path:close()
    -- Make second polyline
    path:moveTo(10,10)
    [...] 
    path:close()
poly = path:getOutline()
poly[1]:draw()
poly[2]:draw()
```
- [ ] **ofPath:getCommands() → vector(ofPathCommands)** 
Not sure how often this is used.

### ofTrueTypeFont

- [ ] **ofTrueTypeFont:getStringAsPoints() → vector(ofPath)**
This might actually be useful, the other functions to work with font outlines like _ofTTF:getCharacterAsPoints()_ take an [unsigned int](https://github.com/openframeworks/openFrameworks/blob/2c036d023e7d6552afd7438a2fd33c87c5a47461/libs/openFrameworks/graphics/ofTrueTypeFont.cpp#L949), I'm not sure how to pass this in Loaf.

##

Then I think that _ofMesh_ and _ofVboMesh_ will be a bit more complicated, as they have a lot of functions returning vectors (getIndices, getColors, getNormals, getTexCoords). I tried quickly and only getVertices seems to be wrapped correctly.

**Comment by danomatika** [comment]
>I tried quickly and only getVertices seems to be wrapped correctly.

Note: Those are explicitly *ignored* when making the bindings. I don't try to make the Lua bindings cover 100% of the OF API. For things which have a function with arguments and an alternative version with a vector, I started by ignoring the vector version.

**Comment by danomatika** [comment]
Ok, all of these type vectors should now be wrapped, including those used by ofMesh. Can you try this test build?

http://docs.danomatika.com/releases/loaf/loaf-1.6.0-test1-macos.zip

**Comment by danomatika** [comment]
I'm going to assume they work now. Please test and reopen if not.
